### ISSUE TITLE
KiotaでAPIクライアントの作成ができない。

### ISSUE THREAD

**Issue by AyatoYoshizawa** [AyatoYoshizawa/todo_app#6]
- エラー文
C:\repo\todo_app\win-x64>kiota generate --openapi openapi.json --language typescript
Warning: the TypeScript language is in preview (Preview) some features are not fully supported and source breaking changes will happen with future updates.
crit: Kiota.Builder.KiotaBuilder[0]
      error generating the client: A duplicate label already exists for this node: default (Parameter 'label')

- やったこと
https://127.0.01/openapi.jsonの内容をコピーしてC:\repo\todo_app\win-x64\openapi.jsonにペースト。

kiotaがバージョン3.1に対応していないのと、serverのurlを追加するように言われたので、
openapi.jsonを直接編集して、openapiのバージョンを3.0に変更し、serverのurlを追加した。

その後上記のkiotaコマンドを実行したら、defaultというラベルが重複しているというエラーが出た。

openapi.jsonの中身をみてもdefaultという内容はどこにもなかった。

**Comment by AyatoYoshizawa** [comment]
app = FastAPI()
の中身を指定してopenapiのversionを指定する方法も試したが、反映されなかった。

**Comment by jhelom** [comment]
こっちで試してみるので openapi.json を、この Issue に添付してくれ。

**Comment by AyatoYoshizawa** [comment]
[openapi.json](https://github.com/AyatoYoshizawa/todo_app/files/15149814/openapi.json)

**Comment by jhelom** [comment]
違うかもしれないけど、openapi.json の 172行目にエラーがある。なので kiota もエラーを吐いているのかもしれない。

スキーマを見ると `task` の `id` の型は `anyOf` になっているので `type` の↓うちどれか、という事なのだけれども

```
integer
`null`
```

となっているので、`null` を指定しているのがダメらしい。

今、わかるのはここまで。
もうちょっと調べ見て、なんか分かったら共有する。

**Comment by jhelom** [comment]
![2024-04-29_22h39_56](https://github.com/AyatoYoshizawa/todo_app/assets/1127424/cad8ecf9-5e8f-47ec-bfc9-49d8a21d7b2e)

**Comment by AyatoYoshizawa** [comment]
OK。わかった

**Comment by jhelom** [comment]
Kiota でAPIクライアントを生成できるように修正した。

takashi ブランチを作成して、そこで修正作業をした。
develop ブランチへのプルリクエストしたので差分確認（結構あるけど）してから develop にマージして。
やり分からなければ聞いてちょうだい。

https://github.com/AyatoYoshizawa/todo_app/pull/7/commits/6cbe7001284be5861aa46c658c669d64f2590f19

**Comment by jhelom** [comment]
もうちょっと詳しく説明

1. APIのパスを修正した。/tasks/create や tasks/update といったよう動詞を入れた。これは kiota がHTTPメソッドが違うけど同じパス（例えば GET /tasks/{id} と DELETE /tasks/{id} など）を認識できない不具合があるらしく、これを回避するため。kiota が なんか重複しているよエラーを出していたのは、これらしい。
3. FastAPI が出力する openapi のバージョンを 3.0.3 になるようにした。これも kiota が openapi の最新バージョンに未対応のため。
2. SQLAlchemy のデータモデルと、HTTPリクエスト・レスポンスで使うスキーマモデル(Pydantic)を分けた。 schemas.py に実装。
4. SQLAlchemy の使い方で query は古い書き方なので scalars を使うようにした。このあたりはネットだと古いのが氾濫しているので（特に日本語）、それを学習している ChatGPT も古い方法を提示することが多い。最新情報は英語の公式ドキュメントを参照して。https://docs.sqlalchemy.org/en/20/orm/quickstart.html
5. openapi.json から APIクライアントを作成すバッチファイルを作成した。api-client-generate.bat。これ一発で、frontend/src/api 以下に生成される。

なお、kiota が生成した APIクライアントの動作確認は、まだしていない。

kiota がダメな場合は、 swagger editor の webサイトで生成する方法を試してみることにしよう。メニューで file > import して generate client すると zipファイルでダウンロードできる。

axios
https://axios-http.com/ja/docs/intro

![2024-04-30_06h34_27](https://github.com/AyatoYoshizawa/todo_app/assets/1127424/75fdaa3e-2ca9-46a7-8607-d979ea3c6343)

ということで、よろしく。

**Comment by AyatoYoshizawa** [comment]
OK、ありがとう。

**Comment by jhelom** [comment]
あと、シンプルにするデータモデルから deadline を削除した。
